- name: loops with package
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install software
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
  