- name: functions
  hosts: local
  connection: local
  vars:
    tags:
      application: payment
      environment: prod 

  tasks:
  - name: dictionary functions
    ansible.builtin.debug:
      msg: "The env is: {{ tags | dict2items }}"