- name: play level vars
  hosts: local
  connection: local
  vars:
    course: DevOps
    duration: 5months
    trainer: Siva
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course is: {{ course }}, {{ duration }}, {{ trainer }} "

 
  