- name: play with variable
  hosts: local
  connection: local
  vars:
    course: DevOps
    duration: 6months
    trainer: sivareddy
  tasks:
  - name: printing the course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ course }}, Duration: {{ duration }}, Trainer: {{ trainer }}"