- name: variables with file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "The course is: {{ Course }}, {{ Duration }}, {{ Trainer }}"