- name: vars from file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: prointing vars
    ansible.builtin.debug:
      msg: "Course Name is: {{ Course }}, Duration is: {{ Duration }}, Trainer is: {{ Trainer }}"