- name: vars with prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: user
    prompt: UserName
    private: false
  - name: password
    prompt: Password
    private: true
  tasks:
  - name: printing user name & password
    ansible.builtin.debug:
      msg: "Provide Username: {{ user }}, Provide Password: {{ password }}"  
